"""Add column price to Item model crud ops

Revision ID: 70a88dbc1d96
Revises: a49a8a15d5ba
Create Date: 2024-05-13 15:34:25.069512

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '70a88dbc1d96'
down_revision = 'a49a8a15d5ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
